### ISSUE TITLE
Neither the credentials or download process initialized!  (Again)

### ISSUE THREAD

**Issue by Mikester-Calgary** [hdus/SRTM-Downloader#16] opened 2021-01-30 16:41 UTC
This is a reoccurrence of an old issue.
NASA's data service appears to be up again but is not able to be accessed/downloaded by the SRTM QGIS plugin.
-The plugin itself seems to run fine.
-No credential page is offered after selection of extent area.
-No images are downloaded.

**Comment by jameshgrn** [comment] 2021-02-01 05:06
I am also having this problem with QGIS 3.14. Running a Mac OS on Big Sur. The credentials page doesn't pop up

**Comment by hdus** [comment] 2021-02-01 08:44
NASA has changed the download URL. It's fixed with release 3.1.10.

**Closed as completed by hdus** 2021-02-01 08:44 UTC

**Comment by PeterSprague** [comment] 2021-02-24 20:11
Seems like 3.1.10 has not fixed this.  Same issue for me today

**Comment by hdus** [comment] 2021-02-25 08:30
I can't reproduce the issue. For me it works fine.
